### ISSUE TITLE
Library doesn't support path parameters

### ISSUE THREAD

**Issue by colinodell** [DerManoMann/openapi-verifier#41]
`OpenApiSpecificationLoader::findPath()` fails to match specification paths using [path parameters](https://swagger.io/docs/specification/describing-parameters/#path-parameters) like `/users/{username}` to actual request paths like `/users/bob`.  It seems to be looking for a path literally named `/users/{username}` instead of realizing that `{username}` may contain any value.

**Comment by MattyRad** [comment]
Yes, I ran into this as well. The quick fix was just to use the placeholder path as the function argument.

Not ideal, but personally I'm ok with it, as I'm guessing that it may take quite a bit of extra code (and mental energy) to parse and regex match the path.

**Comment by DerManoMann** [comment]
I suppose the code could do a lookup of the current route using framework code and get the placeholder path from that. Hmm, might be interesting... (Finally!)
